services:
  zot:
    image: ghcr.io/project-zot/zot-linux-amd64:v2.1.14
    container_name: zot-registry
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/zot        # 镜像数据持久化
      - ./config.json:/etc/zot/config.json:ro
      - ./.htpasswd:/etc/zot/htpasswd:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
